import avatarIcon from "./assets/icon_avatar.svg";

export const DUMMY_CHAT_LIST = [
  {
    avatar: [avatarIcon],
    name: "Adam",
    id: 1,
    groupChat: false,
    members: ["1", "2"],
    // lastMessage: "This is the last message.",
  },
  {
    avatar: [avatarIcon],
    name: "Adam",
    id: 2,
    groupChat: false,
    members: ["1", "2"],
    // lastMessage: "This is the last message.",
  },
  {
    avatar: [avatarIcon],
    name: "Adam",
    id: 3,
    groupChat: false,
    members: ["1", "2"],
    // lastMessage: "This is the last message.",
  },
  {
    avatar: [avatarIcon],
    name: "Adam",
    id: 4,
    groupChat: false,
    members: ["1", "2"],
    // lastMessage: "This is the last message.",
  },
  {
    avatar: [avatarIcon],
    name: "Adam",
    id: 5,
    groupChat: false,
    members: ["1", "2"],
    // lastMessage: "This is the last message.",
  },
  {
    avatar: [avatarIcon],
    name: "Adam",
    id: 6,
    groupChat: false,
    members: ["1", "2"],
    // lastMessage: "This is the last message.",
  },
  {
    avatar: [avatarIcon],
    name: "Adam",
    id: 7,
    groupChat: false,
    members: ["1", "2"],
    // lastMessage: "This is the last message.",
  },
  {
    avatar: [avatarIcon],
    name: "Adam",
    id: 8,
    groupChat: false,
    members: ["1", "2"],
    // lastMessage: "This is the last message.",
  },
  {
    avatar: [avatarIcon],
    name: "Adam",
    id: 9,
    groupChat: false,
    members: ["1", "2"],
    // lastMessage: "This is the last message.",
  },
  {
    avatar: [avatarIcon],
    name: "Adam",
    id: 10,
    groupChat: false,
    members: ["1", "2"],
    // lastMessage: "This is the last message.",
  },
  {
    avatar: [avatarIcon],
    name: "Adam",
    id: 11,
    groupChat: false,
    members: ["1", "2"],
    // lastMessage: "This is the last message.",
  },
  {
    avatar: [avatarIcon],
    name: "Adam",
    id: 12,
    groupChat: false,
    members: ["1", "2"],
    // lastMessage: "This is the last message.",
  },
  {
    avatar: [avatarIcon],
    name: "Adam",
    id: 13,
    groupChat: false,
    members: ["1", "2"],
    // lastMessage: "This is the last message.",
  },
  {
    avatar: [avatarIcon],
    name: "Adam",
    id: 14,
    groupChat: false,
    members: ["1", "2"],
    // lastMessage: "This is the last message.",
  },
];
